# Generated by Django 2.1.1 on 2018-10-13 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.CharField(default='高一秋季0', max_length=16)),
                ('time', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='未命名', max_length=16)),
                ('gender', models.CharField(default='男', max_length=8)),
                ('gradeClass', models.DecimalField(decimal_places=2, default=2021.17, max_digits=8)),
                ('school', models.CharField(default='实验中学', max_length=20)),
                ('tel', models.CharField(default='130', max_length=16)),
                ('telF', models.CharField(default='130', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maths', models.IntegerField(default=0)),
                ('mathsSort', models.IntegerField(default=1000)),
                ('chinese', models.IntegerField(default=0)),
                ('chineseSort', models.IntegerField(default=1000)),
                ('english', models.IntegerField(default=0)),
                ('englishSort', models.IntegerField(default=1000)),
                ('physics', models.IntegerField(default=0)),
                ('physicsSort', models.IntegerField(default=1000)),
                ('chymistry', models.IntegerField(default=0)),
                ('chymistrySort', models.IntegerField(default=1000)),
                ('biology', models.IntegerField(default=0)),
                ('biologySort', models.IntegerField(default=1000)),
                ('history', models.IntegerField(default=0)),
                ('historySort', models.IntegerField(default=1000)),
                ('politics', models.IntegerField(default=0)),
                ('politicsSort', models.IntegerField(default=1000)),
                ('geography', models.IntegerField(default=0)),
                ('geographySort', models.IntegerField(default=1000)),
                ('total', models.IntegerField(default=0)),
                ('totalSort', models.IntegerField(default=1000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoreperson', to='Model.Person')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoreexam', to='Model.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='TopList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(default='综合', max_length=8)),
                ('score', models.IntegerField(default=0)),
                ('scoreSort', models.IntegerField(default=1000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topperson', to='Model.Person')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topexam', to='Model.Exam')),
            ],
        ),
    ]
