# Generated by Django 2.2.7 on 2020-06-10 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regression',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kRegression', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('eRegression', models.DecimalField(decimal_places=0, default=0.0, max_digits=8)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regcourse', to='Model.Course')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regperson', to='Model.Person')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regexam', to='Model.Exam')),
            ],
        ),
    ]
